version: "3.9"

services:
  go-baseline:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_INDEX=0
      - REDIS_PASSWORD=
      - KAFKA_BROKERS=host.docker.internal:9092
      - KAFKA_GROUP_ID=dt-local
      - PRODUCER_TOPICS="placeholder_dlq:placeholder_dlq;placeholder:placeholder"
      - CONSUMER_TOPICS="placeholder:placeholder-record"
      - HTTP_PORT=8080
      - SHORT_TIMEOUT=10
      - ALPHA_URL=host.docker.internal:8700
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=username
      - DB_PASSWORD=password1234
      - DB_NAME=placeholder
      - DB_SCHEMA=placeholder
      - DB_DRIVER=postgres
      - DB_SSL_MODE=disable
