version: "3.9"

services:
  go-baseline:
    build: .
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_INDEX=0
      - REDIS_PASSWORD=
      - KAFKA_BROKERS=host.docker.internal:9092
      - KAFKA_GROUP_ID=dt-local
      - PRODUCER_TOPICS="transaction_dlq:dt-transaction_dlq;transaction:dt-transaction"
      - CONSUMER_TOPICS="transaction:dt-transaction"
      - HTTP_PORT=8080
      - SHORT_TIMEOUT=10
      - GRPC_PORT=50051
