// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dityuiri/go-baseline/repository (interfaces: IStockRepository)

// Package repository_mock is a generated GoMock package.
package repository_mock

import (
	reflect "reflect"

	model "github.com/dityuiri/go-baseline/model"
	gomock "github.com/golang/mock/gomock"
)

// MockIStockRepository is a mock of IStockRepository interface.
type MockIStockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIStockRepositoryMockRecorder
}

// MockIStockRepositoryMockRecorder is the mock recorder for MockIStockRepository.
type MockIStockRepositoryMockRecorder struct {
	mock *MockIStockRepository
}

// NewMockIStockRepository creates a new mock instance.
func NewMockIStockRepository(ctrl *gomock.Controller) *MockIStockRepository {
	mock := &MockIStockRepository{ctrl: ctrl}
	mock.recorder = &MockIStockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStockRepository) EXPECT() *MockIStockRepositoryMockRecorder {
	return m.recorder
}

// GetStockInfo mocks base method.
func (m *MockIStockRepository) GetStockInfo(arg0 string) (*model.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockInfo", arg0)
	ret0, _ := ret[0].(*model.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockInfo indicates an expected call of GetStockInfo.
func (mr *MockIStockRepositoryMockRecorder) GetStockInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockInfo", reflect.TypeOf((*MockIStockRepository)(nil).GetStockInfo), arg0)
}

// SetStockInfo mocks base method.
func (m *MockIStockRepository) SetStockInfo(arg0 model.Stock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStockInfo", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStockInfo indicates an expected call of SetStockInfo.
func (mr *MockIStockRepositoryMockRecorder) SetStockInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStockInfo", reflect.TypeOf((*MockIStockRepository)(nil).SetStockInfo), arg0)
}
