// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dityuiri/go-baseline/proxy (interfaces: IAlphaProxy)

// Package proxy_mock is a generated GoMock package.
package proxy_mock

import (
	context "context"
	"github.com/dityuiri/go-baseline/model/alpha"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIAlphaProxy is a mock of IAlphaProxy interface.
type MockIAlphaProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIAlphaProxyMockRecorder
}

// MockIAlphaProxyMockRecorder is the mock recorder for MockIAlphaProxy.
type MockIAlphaProxyMockRecorder struct {
	mock *MockIAlphaProxy
}

// NewMockIAlphaProxy creates a new mock instance.
func NewMockIAlphaProxy(ctrl *gomock.Controller) *MockIAlphaProxy {
	mock := &MockIAlphaProxy{ctrl: ctrl}
	mock.recorder = &MockIAlphaProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAlphaProxy) EXPECT() *MockIAlphaProxyMockRecorder {
	return m.recorder
}

// GetPlaceholderStatus mocks base method.
func (m *MockIAlphaProxy) GetPlaceholderStatus(arg0 context.Context, arg1 alpha.AlphaRequest) (alpha.AlphaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaceholderStatus", arg0, arg1)
	ret0, _ := ret[0].(alpha.AlphaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaceholderStatus indicates an expected call of GetPlaceholderStatus.
func (mr *MockIAlphaProxyMockRecorder) GetPlaceholderStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaceholderStatus", reflect.TypeOf((*MockIAlphaProxy)(nil).GetPlaceholderStatus), arg0, arg1)
}
