@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Requester
Requester -> GRPCServer: rpc GetSummary(ctx, stock)
activate GRPCServer
activate Redis
GRPCServer -> Redis: GetStockInfo(transaction.stockCode)
Redis --> GRPCServer: stock info
alt error == redis.NIL
    GRPCServer --> Requester: codes.NotFound
else if other error
    GRPCServer --> Requester: codes.Internal
end

GRPCServer --> Requester: Stock summary response

deactivate Redis
deactivate GRPCServer




@enduml